export const WORKS_DATA = {
  hero: {
    title: 'Works',
    thumbnail: '/works-hero.jpg',
  },
  works: [
    {
      id: '1',
      title: 'portfolio',
      span: '2023/04~05',
      desc: '説明です。',
      stacks: 'Next.js, TypeScript, Chakra UI',
      img_path: '',
      product_url: '#',
    },
    {
      id: '2',
      title: 'Simple Memo',
      span: '2023/03~04',
      desc: '説明です。',
      stacks: 'Vue, Pinia, TypeScript',
      img_path: '/workcards/simple-memo.png',
      product_url: 'https://simple-memo-oa93ktfxi-seiya-tagami.vercel.app/',
    },
    {
      id: '3',
      title: 'Simple Memo',
      span: '2023/03~04',
      desc: '説明です。',
      stacks: '',
      img_path: '',
      product_url: '',
    },
    {
      id: '4',
      title: 'POSSE webapp',
      span: '2023/09~12',
      desc: '大学生プログラミング学習コミュニティ内で制作した学習管理アプリケーションです。',
      stacks: 'Vanilla JS, PHP, SCSS',
      img_path: '',
      product_url: '#',
    },
    {
      id: '5',
      title: 'POSSE website',
      span: '2022/06~12',
      desc: '大学生プログラミング学習コミュニティ内で制作したコミュニティ紹介サイトです。',
      stacks: 'Vanilla JS, PHP, SCSS',
      img_path: '',
      product_url: '#',
    },
  ],
}
