export const WORKS_DATA = {
  hero: {
    title: 'Works',
    thumbnail: '/heros/works.jpg',
  },
  works: [
    {
      id: '0',
      title: 'todo-generator',
      span: '2023/05',
      desc: 'Qwik1.0がリリースされ、どんなフレームワークなのか触れてみたいと思い、このアプリケーションを開発してみました。自分のタスクがなくなって、もう何もすることがないという人におすすめです。',
      stacks: 'Qwik City, Azure Cognitive Services Translator',
      img_path: '/workCards/todo-generator.png',
      product_url: 'https://todo-generator.vercel.app/',
    },
    {
      id: '1',
      title: 'portfolio',
      span: '2023/04~05',
      desc: '私のポートフォリオサイトです。これから、色々と載せていきます。',
      stacks: 'Next.js, TypeScript, Chakra UI',
      img_path: '/workCards/seiyaCode.png',
      product_url: '/',
    },
    {
      id: '2',
      title: 'Simple Memo',
      span: '2023/03~05',
      desc: 'シンプルで直感的な操作性を意識したメモアプリです。Nest.jsによるapi開発にも、初めて取り組んでみました。なお、Vercelにデプロイしているのは、フロントエンドのみで動作するものとなります。',
      stacks: 'Vue, TypeScript, Nest.js, Prisma',
      img_path: '/workCards/simple-memo.png',
      product_url: 'https://simple-memo.vercel.app/',
    },
    {
      id: '3',
      title: 'Memory Game',
      span: '2022/07~08',
      desc: 'ドットインストールで学んだことを活かしつつ、自分なりに和風なテイストを加え作成した、神経衰弱ゲームアプリです。',
      stacks: 'Vanilla JS, SCSS',
      img_path: '/workCards/memorygame.png',
      product_url: '#',
    },
    {
      id: '4',
      title: 'POSSE webapp',
      span: '2022/09~12',
      desc: '大学生プログラミング学習コミュニティ内で制作した学習管理アプリケーションです。',
      stacks: 'Vanilla JS, Chart.js, PHP, SCSS',
      img_path: '/workCards/p-webapp.png',
      product_url: '#',
    },
    {
      id: '5',
      title: 'POSSE website',
      span: '2022/06~12',
      desc: '大学生プログラミング学習コミュニティ内で制作したコミュニティ紹介サイトです。',
      stacks: 'Vanilla JS, PHP, SCSS',
      img_path: '/workCards/p-website.png',
      product_url: '#',
    },
  ],
}
