import Head from 'next/head'
import React, { FC } from 'react'

type MetaProps = {
  title: string
}
const Meta: FC<MetaProps> = (props) => {
  const { title } = props;
  return (
    <Head>
      <title>{title} - SeiyaCode</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}

export default Meta